### ISSUE TITLE
Error on acid_tbc.sql

### ISSUE THREAD

**Issue by aaroncdc** [ACID-Scripts/TBC#28]
ERROR 1064 (42000) at line 4787: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EL (5 Yards Min Range)
('183104','1831','9','5','100','1','9','80','1000','1000'' at line 3522

This line contains a stray string:

> ('183103','1831','9','5','100','1','5','30','2300','3900','11','6660','1','0','40','2','0','0','0','0','0','0','Scarlet Hunter - Cast Shoot and Set Ranged Weapon Model (Phase 1)'),**EL (5 Yards Min Range)**

**Comment by cala** [comment]
Closed by https://github.com/ACID-Scripts/TBC/commit/6f4a81c482c5ad7eb77a2cf08f5bea0deea0bff0
